counter: 5
role_mapping: 
  "liugq.infinilabs.com": [ "ReadonlyUI" ]

modules:
- module: crawler
  enabled: true
  namespace: "hello world"
  liked: 1235

- module: parser
  enabled: false
  parser_id: "abc12"

config_map_array:
- if:
  name1: value1
- key2:
  name2: value2