// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  elastic

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AliasDetailInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AliasDetailInfo ) UnmarshalJSON([]byte) error { return nil }
func ( AliasDetailInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AliasDetailInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AliasDetailInfo *AliasDetailInfo

func ( AliasIndex ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AliasIndex ) UnmarshalJSON([]byte) error { return nil }
func ( AliasIndex ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AliasIndex ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AliasIndex *AliasIndex

func ( AliasInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AliasInfo ) UnmarshalJSON([]byte) error { return nil }
func ( AliasInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AliasInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AliasInfo *AliasInfo

func ( BulkActionMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BulkActionMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( BulkActionMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BulkActionMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BulkActionMetadata *BulkActionMetadata

func ( BulkIndexMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BulkIndexMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( BulkIndexMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BulkIndexMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BulkIndexMetadata *BulkIndexMetadata

func ( BulkResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BulkResponse ) UnmarshalJSON([]byte) error { return nil }
func ( BulkResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BulkResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BulkResponse *BulkResponse

func ( CatIndexResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CatIndexResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CatIndexResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CatIndexResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CatIndexResponse *CatIndexResponse

func ( DeleteByQueryResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteByQueryResponse ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteByQueryResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteByQueryResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteByQueryResponse *DeleteByQueryResponse

func ( IndexInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexInfo ) UnmarshalJSON([]byte) error { return nil }
func ( IndexInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexInfo *IndexInfo

func ( IndexStats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexStats ) UnmarshalJSON([]byte) error { return nil }
func ( IndexStats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexStats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexStats *IndexStats

func ( NodesInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodesInfo ) UnmarshalJSON([]byte) error { return nil }
func ( NodesInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodesInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodesInfo *NodesInfo

func ( NodesResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodesResponse ) UnmarshalJSON([]byte) error { return nil }
func ( NodesResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodesResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodesResponse *NodesResponse

func ( ReindexResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReindexResponse ) UnmarshalJSON([]byte) error { return nil }
func ( ReindexResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ReindexResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReindexResponse *ReindexResponse

func ( ShardInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ShardInfo ) UnmarshalJSON([]byte) error { return nil }
func ( ShardInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ShardInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ShardInfo *ShardInfo

func ( Stats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Stats ) UnmarshalJSON([]byte) error { return nil }
func ( Stats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Stats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Stats *Stats
