// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  elastic

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AliasDetailInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AliasDetailInfo ) UnmarshalJSON([]byte) error { return nil }
func ( AliasDetailInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AliasDetailInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AliasDetailInfo *AliasDetailInfo

func ( AliasIndex ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AliasIndex ) UnmarshalJSON([]byte) error { return nil }
func ( AliasIndex ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AliasIndex ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AliasIndex *AliasIndex

func ( AliasInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AliasInfo ) UnmarshalJSON([]byte) error { return nil }
func ( AliasInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AliasInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AliasInfo *AliasInfo

func ( BasicAuth ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BasicAuth ) UnmarshalJSON([]byte) error { return nil }
func ( BasicAuth ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BasicAuth ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BasicAuth *BasicAuth

func ( BulkActionMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BulkActionMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( BulkActionMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BulkActionMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BulkActionMetadata *BulkActionMetadata

func ( BulkIndexMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BulkIndexMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( BulkIndexMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BulkIndexMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BulkIndexMetadata *BulkIndexMetadata

func ( BulkResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BulkResponse ) UnmarshalJSON([]byte) error { return nil }
func ( BulkResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BulkResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BulkResponse *BulkResponse

func ( CatIndexResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CatIndexResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CatIndexResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CatIndexResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CatIndexResponse *CatIndexResponse

func ( CatNodeResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CatNodeResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CatNodeResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CatNodeResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CatNodeResponse *CatNodeResponse

func ( CatShardResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CatShardResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CatShardResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CatShardResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CatShardResponse *CatShardResponse

func ( DeleteByQueryResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DeleteByQueryResponse ) UnmarshalJSON([]byte) error { return nil }
func ( DeleteByQueryResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DeleteByQueryResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DeleteByQueryResponse *DeleteByQueryResponse

func ( ElasticsearchConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ElasticsearchConfig ) UnmarshalJSON([]byte) error { return nil }
func ( ElasticsearchConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ElasticsearchConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ElasticsearchConfig *ElasticsearchConfig

func ( ElasticsearchMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ElasticsearchMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( ElasticsearchMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ElasticsearchMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ElasticsearchMetadata *ElasticsearchMetadata

func ( ErrorResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ErrorResponse ) UnmarshalJSON([]byte) error { return nil }
func ( ErrorResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ErrorResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ErrorResponse *ErrorResponse

func ( GeoLocation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GeoLocation ) UnmarshalJSON([]byte) error { return nil }
func ( GeoLocation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GeoLocation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GeoLocation *GeoLocation

func ( HostMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* HostMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( HostMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* HostMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_HostMetadata *HostMetadata

func ( IndexConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexConfig ) UnmarshalJSON([]byte) error { return nil }
func ( IndexConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexConfig *IndexConfig

func ( IndexInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexInfo ) UnmarshalJSON([]byte) error { return nil }
func ( IndexInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexInfo *IndexInfo

func ( IndexLevelStats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexLevelStats ) UnmarshalJSON([]byte) error { return nil }
func ( IndexLevelStats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexLevelStats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexLevelStats *IndexLevelStats

func ( IndexMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( IndexMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexMetadata *IndexMetadata

func ( IndexStats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* IndexStats ) UnmarshalJSON([]byte) error { return nil }
func ( IndexStats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* IndexStats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_IndexStats *IndexStats

func ( MetadataConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MetadataConfig ) UnmarshalJSON([]byte) error { return nil }
func ( MetadataConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MetadataConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MetadataConfig *MetadataConfig

func ( MonitorConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MonitorConfig ) UnmarshalJSON([]byte) error { return nil }
func ( MonitorConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MonitorConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MonitorConfig *MonitorConfig

func ( NodeAvailable ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodeAvailable ) UnmarshalJSON([]byte) error { return nil }
func ( NodeAvailable ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodeAvailable ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodeAvailable *NodeAvailable

func ( NodeConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodeConfig ) UnmarshalJSON([]byte) error { return nil }
func ( NodeConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodeConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodeConfig *NodeConfig

func ( NodeMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodeMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( NodeMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodeMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodeMetadata *NodeMetadata

func ( NodesInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodesInfo ) UnmarshalJSON([]byte) error { return nil }
func ( NodesInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodesInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodesInfo *NodesInfo

func ( NodesResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NodesResponse ) UnmarshalJSON([]byte) error { return nil }
func ( NodesResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NodesResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NodesResponse *NodesResponse

func ( ReindexResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReindexResponse ) UnmarshalJSON([]byte) error { return nil }
func ( ReindexResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ReindexResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReindexResponse *ReindexResponse

func ( ShardInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ShardInfo ) UnmarshalJSON([]byte) error { return nil }
func ( ShardInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ShardInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ShardInfo *ShardInfo

func ( Stats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Stats ) UnmarshalJSON([]byte) error { return nil }
func ( Stats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Stats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Stats *Stats

func ( TaskConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TaskConfig ) UnmarshalJSON([]byte) error { return nil }
func ( TaskConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TaskConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TaskConfig *TaskConfig

func ( TraceMeta ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TraceMeta ) UnmarshalJSON([]byte) error { return nil }
func ( TraceMeta ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TraceMeta ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TraceMeta *TraceMeta

func ( UpdateByQueryResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UpdateByQueryResponse ) UnmarshalJSON([]byte) error { return nil }
func ( UpdateByQueryResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UpdateByQueryResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdateByQueryResponse *UpdateByQueryResponse
