// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  elastic

import (
  "github.com/mailru/easyjson/jlexer"
  "github.com/mailru/easyjson/jwriter"
)

func ( ScrollResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ScrollResponse ) UnmarshalJSON([]byte) error { return nil }
func ( ScrollResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ScrollResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ScrollResponse *ScrollResponse

func ( ScrollResponseV7 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ScrollResponseV7 ) UnmarshalJSON([]byte) error { return nil }
func ( ScrollResponseV7 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ScrollResponseV7 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ScrollResponseV7 *ScrollResponseV7
