/* Copyright © INFINI LTD. All rights reserved. */

package easysearch

import (
	"errors"
	"net/http"

	"infini.sh/framework/core/api"
	"infini.sh/framework/core/api/crud"
	httprouter "infini.sh/framework/core/api/router"
	"infini.sh/framework/core/elastic"
	"infini.sh/framework/core/security"
	"infini.sh/framework/core/util"
)

// ──────────────────────────────────────────────────────────────────────────
// Cluster management REST API — public, reusable, ORM-backed.
//
// CRUD over ElasticsearchConfig clusters using only the standard ORM (sqlite
// or any non-elastic store). Routes use the /easysearch/ prefix (not
// /elasticsearch/) so they don't collide with legacy /elasticsearch/ routes.
//
// The five CRUD endpoints are generated by core/api/crud (this module was
// its pilot); only the pre-registration _test probe remains hand-written.
//
// Decoupled from modules/elastic: no live-client registration, no in-memory
// metadata registry. Health status shown in responses is the value persisted
// on each cluster's Labels by the elasticsearch module's health loop.
// ──────────────────────────────────────────────────────────────────────────

// ClusterAPI provides REST CRUD for ElasticsearchConfig clusters. It embeds
// api.Handler for DecodeJSON/WriteJSON/WriteError.
type ClusterAPI struct {
	api.Handler
}

// registerClusterAPI registers the /easysearch/ CRUD routes. Called from
// Module.Setup so every app that registers the easysearch module gets cluster
// management. The /_test route is public (AllowPublicAccess) because it's a
// pre-registration connectivity probe (no cluster exists yet).
func registerClusterAPI() {

	// Generic permission keys for cluster management. Apps assign these to roles
	// to control who can manage clusters.
	var (
		permClusterRead   = security.GetOrInitPermission("generic", "easysearch:cluster", security.Read)
		permClusterCreate = security.GetOrInitPermission("generic", "easysearch:cluster", security.Create)
		permClusterUpdate = security.GetOrInitPermission("generic", "easysearch:cluster", security.Update)
		permClusterDelete = security.GetOrInitPermission("generic", "easysearch:cluster", security.Delete)
		permClusterSearch = security.GetOrInitPermission("generic", "easysearch:cluster", security.Search)
	)
	permissionFor := func(action string) api.PermissionKey {
		switch action {
		case crud.ActionRead:
			return permClusterRead
		case crud.ActionCreate:
			return permClusterCreate
		case crud.ActionUpdate:
			return permClusterUpdate
		case crud.ActionDelete:
			return permClusterDelete
		case crud.ActionSearch:
			return permClusterSearch
		}
		return ""
	}

	// The five standard endpoints are generated (create / _search / get /
	// update / delete — see core/api/crud for the conventions this module
	// used to hand-copy).
	crud.RegisterCRUD[elastic.ElasticsearchConfig](crud.Config[elastic.ElasticsearchConfig]{
		Prefix:             "/easysearch",
		Resource:           "cluster",
		Permission:         permissionFor,
		DefaultQueryFields: []string{"name"},
		MCP:                true,
		PrepareCreate: func(cfg *elastic.ElasticsearchConfig) error {
			if cfg.Name == "" {
				return errors.New("name is required")
			}
			if cfg.ID == "" {
				cfg.ID = util.GetUUID()
			}
			if cfg.Distribution == "" {
				cfg.Distribution = elastic.Elasticsearch
			}
			// Mark as dynamically-managed so the elasticsearch module's health
			// loop persists status for it (the loop keys off this source value).
			cfg.Source = elastic.ElasticsearchConfigSourceElasticsearch
			cfg.Enabled = true
			return nil
		},
		GuardDelete: func(cfg *elastic.ElasticsearchConfig) error {
			if cfg.Reserved {
				return errors.New("reserved cluster cannot be deleted")
			}
			return nil
		},
	})

	// Pre-registration connectivity probe — deliberately bespoke.
	h := &ClusterAPI{}
	api.HandleUIMethod(api.POST, "/easysearch/_test", h.testConnection, api.RequirePermission(permClusterRead), api.AllowOPTIONSS(), api.Feature(api.FeatureCORS))
}

// testConnection — POST /easysearch/_test
// Pre-registration connectivity + version probe via a raw HTTP request. Does
// NOT persist or register the cluster. Public so it works before login is
// required (callers use it to validate a form before creating).
func (h *ClusterAPI) testConnection(w http.ResponseWriter, req *http.Request, _ httprouter.Params) {
	var cfg elastic.ElasticsearchConfig
	if err := h.DecodeJSON(req, &cfg); err != nil {
		h.WriteError(w, err.Error(), http.StatusBadRequest)
		return
	}
	endpoint := cfg.Endpoint
	if endpoint == "" && len(cfg.Endpoints) > 0 {
		endpoint = cfg.Endpoints[0]
	}
	if endpoint == "" {
		h.WriteError(w, "endpoint is required", http.StatusBadRequest)
		return
	}
	if cfg.Distribution == "" {
		cfg.Distribution = elastic.Elasticsearch
	}

	// Shared probe (core/elastic.ProbeCluster): connectivity + version, no
	// adapter build, no persistence.
	version, distribution, err := elastic.ProbeCluster(&cfg)
	if err != nil {
		h.WriteJSON(w, map[string]interface{}{
			"connected":    false,
			"error":        err.Error(),
			"distribution": cfg.Distribution,
		}, http.StatusOK)
		return
	}
	if distribution == "" {
		distribution = cfg.Distribution
	}

	// Warm the shared config-keyed client cache with the probed version, so
	// the eventual create/update builds a client without re-probing.
	// Best-effort: the probe already validated connectivity.
	if version != "" {
		cfg.Version = version
		if distribution != "" {
			cfg.Distribution = distribution
		}
		_, _ = elastic.GetOrCreateClient(cfg)
	}

	h.WriteJSON(w, map[string]interface{}{
		"connected":    true,
		"version":      version,
		"distribution": distribution,
	}, http.StatusOK)
}

// ──────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────
