name: Products Integration Test

on:
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GO_VERSION: 1.23.4
            NODEJS_VERSION: 16.20.2
            JAVA_DISTRIBUTION: temurin
            JAVA_VERSION: 11

        steps:
            - name: Init env
              run: |
                export WORKBASE=$HOME/go/src
                export WORK=$WORKBASE/infini.sh

                echo WORKBASE=$HOME/go/src >> $GITHUB_ENV
                echo WORK=$WORKBASE/infini.sh >> $GITHUB_ENV
                echo EASYSEARCH_INITIAL_ADMIN_PASSWORD=admin >> $GITHUB_ENV
                echo ES_USERNAME=admin >> $GITHUB_ENV
                echo ES_PASSWORD=admin >> $GITHUB_ENV
                echo ES_ENDPOINT=https://127.0.0.1:9200 >> $GITHUB_ENV
                echo EOF=$(date -d "$(date +%Y)-12-31 +1 day -1 day" +%Y-%m-%d) >> $GITHUB_ENV
                echo BUILD_NUMBER=$(date +%Y%m%d) >> $GITHUB_ENV
                echo BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S") >> $GITHUB_ENV
                cat $GITHUB_ENV
                  
            - name: Checkout current repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                path: framework

            - name: Checkout console
              uses: actions/checkout@v4
              with:
                ref: main
                fetch-depth: 0
                repository: infinilabs/console
                path: console

            - name: Checkout gateway
              uses: actions/checkout@v4
              with:
                ref: main
                fetch-depth: 0
                repository: infinilabs/gateway
                path: gateway

            - name: Checkout agent
              uses: actions/checkout@v4
              with:
                ref: main
                fetch-depth: 0
                repository: infinilabs/agent
                path: agent

            - name: Checkout loadgen
              uses: actions/checkout@v4
              with:
                ref: main
                fetch-depth: 0
                repository: infinilabs/loadgen
                path: loadgen

            - name: Checkout framework-vendor
              uses: actions/checkout@v4
              with:
                ref: main
                fetch-depth: 0
                repository: infinilabs/framework-vendor
                path: vendor

            - name: Set up nodejs toolchain
              uses: actions/setup-node@v4
              with:
                node-version: ${{ env.NODEJS_VERSION }}
            
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: |
                  node_modules
                key: ${{ runner.os }}-cnpm-${{ hashFiles('**/package.json') }}
                restore-keys: |
                    ${{ runner.os }}-cnpm-

            - name: Check nodejs toolchain
              run: |
                if ! command -v cnpm >/dev/null 2>&1; then
                  npm install -g rimraf
                  npm install -g cnpm@9.2.0
                fi
                node -v && npm -v && cnpm -v

            - name: Set up go toolchain
              uses: actions/setup-go@v5
              with:
                go-version: ${{ env.GO_VERSION }}
                check-latest: false
                cache: true

            - name: Check go toolchain
              run: go version

            - name: Set up java toolchain
              uses: actions/setup-java@v4
              with:
                distribution: ${{ env.JAVA_DISTRIBUTION }}
                java-version: ${{ env.JAVA_VERSION }}
            
            - name: Check java toolchain
              run: java -version && which java

            - name: Install easysearch and run
              shell: bash
              run: |
                # Install easysearch
                curl -sSL http://get.infini.cloud | bash -s -- -p easysearch -d $HOME/easysearch
                [ -z "$JAVA_HOME" ] || ln -s "$JAVA_HOME" $HOME/easysearch/jdk
                cd $HOME/easysearch && bin/initialize.sh -s && bin/easysearch -d

            - name: Compile products code
              shell: bash
              run: |
                mkdir -p $WORKBASE
                echo Home path is $HOME
                
                echo Check work folder $GITHUB_WORKSPACE
                ln -s $GITHUB_WORKSPACE $WORK
                ls -al $WORK/

                # for console web
                cd $WORK/console/web && echo Compiling code at $PWD ...
                cnpm install --quiet --no-progress && cnpm run build --quiet
                
                # for products
                for p in console gateway agent loadgen; do
                  cd $WORK/$p && echo Compiling $p at $PWD ...
                  OFFLINE_BUILD=true make build
                done
        
            - name: Run gateway test
              shell: bash
              run: |
                cd $WORK/gateway/bin
                sed -i "/ES_USER:/ s/\(.*\: \).*/\1$ES_USERNAME/g" gateway.yml
                sed -i "/ES_PASS:/ s/\(.*\: \).*/\1$ES_PASSWORD/g" gateway.yml
                sed -i "/ES_ENDPOINT:/ s/\(.*\: \).*/\1$ES_ENDPOINT/g" gateway.yml
                echo Running integration test at $PWD ...
                exec $WORK/gateway/bin/gateway

            - name: Run console test
              shell: bash
              run: |
                cd $WORK/console/bin
                echo Running integration test at $PWD ...
                exec $WORK/console/bin/console

            - name: Run loadgen test
              shell: bash
              run: |
                cd $WORK/loadgen/bin
                sed -i "/ES_USERNAME:/ s/\(.*\: \).*/\1$ES_USERNAME/g" loadgen.yml
                sed -i "/ES_PASSWORD:/ s/\(.*\: \).*/\1$ES_PASSWORD/g" loadgen.yml
                sed -i "/ES_ENDPOINT:/ s/\(.*\: \).*/\1$ES_ENDPOINT/g" loadgen.yml
                echo Running integration test at $PWD ...
                $WORK/loadgen/bin/loadgen -d 60

            - name: Run agent test
              shell: bash
              run: |
                cd $WORK/agent/bin
                sed -i "/2900/8080/g" agent.yml
                echo Running integration test at $PWD ...
                exec $WORK/agent/bin/agent